### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by nafergo** [JYamihud/blender-organizer#2]
won't start ehen I try python blender-organizer.py

Gtk-Message: 22:41:02.463: Failed to load module "overlay-scrollbar"
Gtk-Message: 22:41:02.471: Failed to load module "canberra-gtk-module"
destroyed
Traceback (most recent call last):
  File "blender-organizer.py", line 365, in <module>
    drawmain()
  File "blender-organizer.py", line 357, in drawmain
    analytics.draw_analytics(os.getcwd(), drawbox, mainwin)
  File "/home/nafergo/Downloads/blender-organizer-master/py_data/modules/analytics.py", line 82, in __init__
    scenpercent = story_editor.get_scenes_percentage(story)
  File "/home/nafergo/Downloads/blender-organizer-master/py_data/modules/story_editor.py", line 3439, in get_scenes_percentage
    persantage = float(sum(valueslist))/len(valueslist)
ZeroDivisionError: float division by zero

**Comment by nafergo** [comment]
btw the problem seem to be on the latest commits. I used a 4 days ago version (before latest commits) and it runs :)

**Comment by JYamihud** [comment]
If something doesn't run... You need to check if the gtk module installed properly

**Comment by JYamihud** [comment]
> won't start ehen I try python blender-organizer.py
...
> persantage = float(sum(valueslist))/len(valueslist)
> ZeroDivisionError: float division by zero

Got it... It's the bug with the old code i used from the old organizer. Basically there was 0 of something and to know the average of it you have to divide the sum of all instances by the amount. And since there is 0 instances, you divide by 0. And since it's impossible. It gives an error and all freezes.

But in the new organizer update I rewritten that part. And made sure all 0s will be resolved. Tho you probably can still end up in a bad situation if you set your start date and end date to the same day.

**Comment by JYamihud** [comment]
> persantage = float(sum(valueslist))/len(valueslist)
> ZeroDivisionError: float division by zero

Okay got this for myself. And it did return this mistake. I this it's something to do with the lengh of the initial story in the story editor.
Fixed it using

```
    try:
        persantage = float(sum(valueslist))/len(valueslist)
    except:
        persantage = 0.0
```
So far works... Lemmi know about other issues
